# Build Stage
FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build
WORKDIR /source
COPY . .
RUN dotnet restore "./GraphQLDemoAPI/GraphQLDemoAPI.csproj" --disable-parallel
RUN dotnet publish "./GraphQLDemoAPI/GraphQLDemoAPI.csproj" -c release -o /app --no-restore

# Serve Stage
FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build
WORKDIR /app 
COPY --from=build /app ./

EXPOSE 5000

ENTRYPOINT ["dotnet", "GraphQLDemoAPI.dll"]